#将该变量设置为-1，可以禁用HTTP，将其配置成0会在随机端口上启用
server:
  port: 8088
#  servlet:
#    context-path: "/intelligent-load"
#数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/intelligent_load?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    #初始化数据库时遇到错误不要停止
    continue-on-error: true
  #关闭模板引擎缓存
  thymeleaf:
    cache: false
  servlet:
    multipart:
      #上传文件的最大容量
      max-file-size: 1MB
      #整个请求的最大容量
      max-request-size: 10MB
  mvc:
    static-path-pattern: /static/**


#日志配置
logging:
  level:
    com.usst.load.mapper: debug
    com.usst.load.dao: debug
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.usst.load.dao




